---
title: "Reddit"
author: "Regan Yee"
date: "November 12, 2016"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(plotly)
library(dplyr)
setwd("~/Documents/bootcamp007_project/Project3-WebScraping/ReganYee/Wayback")
reddit = readRDS("reddit.RDS")

df = reddit %>% 
  mutate(datehour = sapply(reddit$snapshot_datetime, function(x) substring(x,1,10))) %>% 
  mutate(rank_hour = paste0(datehour,rank)) %>% 
  select(1:10, rank_hour, submit_date, submit_hour)

## Return a list of top 10 items that are unique per day and hour
df_unique_hour = df[!duplicated(df$rank_hour),]
df_unique_hour = df_unique_hour %>% select(snapshot_date, rank, titles, subreddit, upvotes, comments, submitter, snapshot_time, url, submit_datetime, submit_date, submit_hour)

## Reindex row indices
rownames(df_unique_hour) = NULL

df_unique_hour = df_unique_hour %>%
  mutate(snapshot_hour = substring(snapshot_time,1,2))
```

## Questions
- What is the best time to submit content?
- What subreddits produce the most front-page content?

## Data 
- Wayback Machine

## Scraping Workflow

## {.flexbox .vcenter}
<div class="centered">
<font size="+5">Findings</font>
</div>

## Hottest Subreddits by Posts
```{r subreddit_analysis, cache = FALSE, echo = FALSE, message=FALSE}
subreddit_grouped = reddit %>% group_by(subreddit,titles) %>%
  summarize(count=n()) %>% arrange(desc(count))

## Filter on subreddits with more than 10 posts in top10
subreddit_analysis = subreddit_grouped %>% 
  select(subreddit) %>% 
  summarize(count=n()) %>% 
  filter(count >=10) %>% 
  arrange(desc(count))

## Reorder to be descending
subreddit_analysis$subreddit = 
  factor(subreddit_analysis$subreddit, levels = unique(subreddit_analysis$subreddit)[order(subreddit_analysis$count, decreasing = TRUE)])

y <- list(
  title = "Number of Posts")

plot_ly (
  x = subreddit_analysis$subreddit,
  y = subreddit_analysis$count,
  type = 'bar') %>% 
  layout(
    yaxis = y
  )
```

## Hottest Upvote Time (by Month)
```{r reddit_score_plot, cache = FALSE, echo = FALSE, message=FALSE}
reddit_score_mean = df_unique_hour %>% 
  select(snapshot_date,upvotes) %>% 
  group_by(snapshot_date) %>% 
  summarize(avg_score_mean = mean(upvotes))

plot_ly (
  x = reddit_score_mean$snapshot_date,
  y = reddit_score_mean$avg_score_mean,
  type = 'scatter',
  mode = 'markers') %>% 
  layout(
    xaxis=list(
        title = "Date",
        nticks = 4
    ),
    yaxis = list(
      title = "Reddit Score"
    )
  )
```

## Hottest Upvote Time (by Snapshot)
```{r reddit_score_hour, cache = FALSE, echo = FALSE, message=FALSE}
reddit_score_by_hour = df_unique_hour %>% 
  group_by(snapshot_hour) %>% summarize(score_mean = mean(upvotes), score_median = median(upvotes))

x <- list(
  title = "Hour of day(UTC)")
y <- list(
  title = "Reddit Score")

plot_ly (
  x = reddit_score_by_hour$snapshot_hour,
  y = reddit_score_by_hour$score_mean,
  type = 'scatter',
  mode = 'lines',
  name = 'mean') %>% 
  add_trace(
    x = reddit_score_by_hour$snapshot_hour,
    y = reddit_score_by_hour$score_median,
    type = 'scatter',
    mode = 'lines',
    name = 'median'
  ) %>% 
  layout(
    xaxis = x,
    yaxis = y
  )
```

## Hottest Upvote Time (by Submit Time)
```{r reddit_score_submitted, cache = FALSE, echo = FALSE, message=FALSE}
reddit_score_by_submit_hour = df_unique_hour %>% 
  group_by(submit_hour) %>% summarize(score_mean = mean(upvotes), score_median = median(upvotes))

x <- list(
  title = "Hour of day(UTC)")
y <- list(
  title = "Reddit Score")

plot_ly(
    x = reddit_score_by_submit_hour$submit_hour,
    y = reddit_score_by_submit_hour$score_mean,
    type = 'scatter',
    mode = 'lines',
    name = 'mean') %>% 
  add_trace(
    x = reddit_score_by_submit_hour$submit_hour,
    y = reddit_score_by_submit_hour$score_median,
    type = 'scatter',
    mode = 'lines',
    name = 'median') %>% 
  layout(
    xaxis = x,
    yaxis = y
  )
```

## How can I get to the front page?

## Conclusions
