library(ggmap)

data.0 <- read.csv("data.0.csv")
data.1 <- read.csv("data.1.csv")
data.2 <- read.csv("data.2.csv")
data.3 <- read.csv("data.3.csv")
data.4 <- read.csv("data.4.csv")
data.5 <- read.csv("data.5.csv")
data.6 <- read.csv("data.6.csv")
data.7 <- read.csv("data.7.csv")
data.8 <- read.csv("data.8.csv")
data.9 <- read.csv("data.9.csv")
data.10 <- read.csv("data.10.csv")
data.11 <- read.csv("data.11.csv")
data.12 <- read.csv("data.12.csv")
data.13 <- read.csv("data.13.csv")
data.14 <- read.csv("data.14.csv")
data.15 <- read.csv("data.15.csv")
data.16 <- read.csv("data.16.csv")
data.17 <- read.csv("data.17.csv")
data.18 <- read.csv("data.18.csv")
data.19 <- read.csv("data.19.csv")
data.20 <- read.csv("data.20.csv")
data.21 <- read.csv("data.21.csv")
data.22 <- read.csv("data.22.csv")
data.23 <- read.csv("data.23.csv")

Hour <- as.character(c(1:23))
Zoom <- c("Neighborhoods", "Top Locations")
Type <- c("Traffic Related Calls", "Suspicious Circumstances", "Disturbances calls", 
          "Liquor Violation Calls", "Burglary Calls", "Assault Calls")

