# ask whether specific subtypes of adjectives are more common in $ restaurants

rests=read.table("carest_camera.out")
attach(rests)
rests$restdollarsone= (rests$restdollars==1)
rests$logwordlen = log(rests$wordlen+1)
rests$loglength = log(rests$length+1)
rests$lognumitems = log(rests$numitems+1)
rests$adj = log(rests$adj+1)
rests$adjresid = residuals(lm(rests$adj ~ rests$loglength))
rests$generous = log(rests$generous+1)
rests$generousresid = residuals(lm(rests$generous ~ rests$loglength))
rests$choice = log(rests$choice+1)
rests$choiceresid = residuals(lm(rests$choice ~ rests$loglength))
rests$provenance = log(rests$origin+1)
rests$provenanceresid = residuals(lm(rests$provenance ~ rests$loglength))
rests$traditional = log(rests$traditional+1)
rests$traditionalresid = residuals(lm(rests$traditional ~ rests$loglength))
rests$useless = log(rests$useless+1)
rests$vague = rests$useless
rests$vagueresid = residuals(lm(rests$vague ~ rests$loglength))
rests$sensoryadj = log(rests$sensoryadj+1)
rests$sensoryadjresid = residuals(lm(rests$sensoryadj ~ rests$loglength))
rests$participle = log(rests$participle+1)
rests$participleresid = residuals(lm(rests$participle ~ rests$loglength))
attach(rests)

m = glm(rests$restdollarsone ~ category + loglength + lognumitems +vagueresid + sensoryadjresid+participleresid+delicious,family="binomial")
summary(m)
