# ask whether traditional words are more common in $$ restaurants

rests=read.table("carest_camera.out")
attach(rests)
rests$restdollarstwo= (rests$restdollars=="$$")
rests$logwordlen = log(rests$wordlen+1)
rests$loglength = log(rests$length+1)
rests$lognumitems = log(rests$numitems+1)
rests$adj = log(rests$adj+1)
rests$adjresid = residuals(lm(rests$adj ~ rests$loglength))
rests$generous = log(rests$generous+1)
rests$generousresid = residuals(lm(rests$generous ~ rests$loglength))
rests$choice = log(rests$choice+1)
rests$choiceresid = residuals(lm(rests$choice ~ rests$loglength))
rests$provenance = log(rests$origin+1)
rests$provenanceresid = residuals(lm(rests$provenance ~ rests$loglength))
rests$traditional = log(rests$traditional+1)
rests$traditionalresid = residuals(lm(rests$traditional ~ rests$loglength))
attach(rests)
m = glm(rests$restdollarstwo ~ category + loglength + lognumitems +traditionalresid,family="binomial")
summary(m)
