shinyUI(navbarPage('Storm Events in U.S. 2007 - 2016',
                   theme = shinythemes::shinytheme('superhero'),
                   
                   tabPanel('Storm Events on Map',
                            div(class="outer",
                                tags$head(
                                  includeCSS("styles.css"),
                                  includeScript("gomap.js")),
                            leafletOutput('map', width = '100%', height = '100%'), 
                            absolutePanel(id = 'map_options', fixed = F, draggable = F,
                                          top = 50, left = 50, right ='auto', bottom = 'auto',
                                          width = 280, height = 'auto',
                                          cursor = 'inherit',
                                          h3(img(src = 'cloud.png', height = 40, width = 40),
                                             'Storm & Loss'),
                                          checkboxGroupInput('top6',
                                                             h4('Select storm event type:'),
                                                             choices = top6,
                                                             selected = c('Tornado', 'Thunderstorm Wind')),
                                          selectInput('loss',
                                                      h4('Select loss type:'),
                                                      choices = loss,
                                                      selected = 'DAMAGE_PROPERTY'),
                                          sliderInput('year',h4('Year'),
                                                      min = 2007, max = 2016, value = 2015:2016)),
                            absolutePanel(id = 'box', fixed = F, draggable = T,
                                          top = 300, left = 'auto', right = 10, bottom = 'auto',
                                          width = 300, height = 'auto', style = 'opacity: 0.8',
                                          cursor = 'inherit',
                                          plotOutput('bar', height = 300))
                            )),
                   
                   tabPanel('Storms on Time Series',
                            fluidRow(
                              column(1),
                              column(3,
                                     h2(''),
                                     h4('Time Series'),
                                     br('Interactive graphs:'),
                                     br('- Move the cursor along with the lines, the corresponding storm types and numbers will be shown at the top right.'),
                                     br('- Drag the selectors at the bottom, either one of them, to change the time range.'),
                                     br('- Change the roll period number at the bottom left, the average number of storms will be changed based on the roll period(months) you choose.'),
                                     br(),
                                     br(),
                                     br(),
                                     br('The information shown in the graphs:'),
                                     br('- The number of every storm type happened in every month, and the corresponding number of deaths.'),
                                     br('- The trend of storms: the peak, the pattern, inference for future.'),
                                     br('- The possible relation between storms and deaths.'),
                                     br()),
                               column(7,
                                     h2(''),
                                     dygraphOutput('dygraph1'),
                                     hr(),
                                     dygraphOutput('dygraph2')),
                               column(1))
                            ),

                   tabPanel('Fatality',
                            fluidRow(
                              column(1),
                              column(6,
                                     h2('Fatality: Location, Gender, Age'),
                                     plotOutput('barplt1'),
                                     hr(),
                                     plotOutput('barplt2')),
                              column(4,
                                     br(),
                                     br(),
                                     br(),
                                     br(),
                                     plotOutput('boxplt', height = 180, width = 270),
                                     h4('Graphs can answer...'),
                                     br('- What locations are more dangerous during a storm?'),
                                     br('- What is the gender ratio in each location?'),
                                     br('- What is the age range of deaths?'),
                                     br('- Which storm type are more dangerous?'),
                                     br('- ...')),
                              column(1))
                            ),
                   
                   tabPanel('Word Cloud',   
                            fluidRow(
                              column(1),
                              column(3,
                                     h2('Word Cloud'),
                                     br(),
                                     br(),
                                     sliderInput('min_freq',
                                                 h4('Minimum Frequency:'),
                                                 min = 1500,  max = 120000, value = 20000),
                                     sliderInput('max_wds',
                                                 h4('Maximum Number of Words:'),
                                                 min = 1,  max = 1000,  value = 400)),
                              column(7,
                                     h3('What are the words used most often'),
                                     h3('in the storm narrative?'),
                                     plotOutput('wordcloud',height = 500)),
                              column(1))
                            ),
                   
                   tabPanel('About',
                            fluidRow(
                              column(1),
                              column(9,
                                     h2('About This Shiny App'),
                                     hr(),
                                     h3('Dataset:'),
                                     a('NOAA',href="http://www.noaa.gov", target = "_blank"),
                                     br('National Oceanic and Atmospheric Administration'),
                                     br(),
                                     h3('Codes:'),
                                     a('NYC Data Science Academy Blog',href="http://blog.nycdatascience.com/student-works/storm-shiny/", target = "_blank"),
                                     br(),
                                     br()),
                              column(1)),
                            absolutePanel(id = 'ds', fixed = F, draggable = F,
                                          top = 300, left = 290, right = 'auto', bottom = 'auto',
                                          width = 600, height = 'auto', style = 'opacity: 0.8',
                                          cursor = 'inherit',
                                          img(src = "ds.png", width = 600))
                            )
                   
               
))