library(flexclust)
dm_train <- readRDS("dm_train.RDS")
dm_test <- readRDS("dm_test.RDS")
dm_train_hclust <- as.data.frame(dm_train)
dm_test_hclust <- as.data.frame(dm_test)
#names(dm_train_kmeans)
set.seed(123)
test_idx <- sample(1:nrow(dm_test_hclust), 0.01*nrow(dm_test_hclust))
set.seed(123)
train_idx <- sample(1:nrow(dm_train_hclust), 0.01*nrow(dm_train_hclust))
dm_train_hclust_1 <- dm_train_hclust[train_idx,]
dm_test_hclust_1 <- dm_test_hclust[test_idx,]
dm_train_hclust_1 <- scale(dm_train_hclust_1)
dm_test_hclust_1 <- scale(dm_test_hclust_1)
dist_train <- dist(dm_train_hclust_1)
dist_test <- dist(dm_test_hclust_1)
train_single <- hclust(dist_train, method = "single")
train_complete <- hclust(dist_train, method = "complete")
train_average <- hclust(dist_train, method = "average")
test_single <- hclust(dist_test, method = "single")
test_complete <- hclust(dist_test, method = "complete")
test_average <- hclust(dist_test, method = "average")


par(mfrow = c(1, 3))
plot(train_single, hang = -1, main = "Dendrogram of Single Linkage")
plot(train_complete, hang = -1, main = "Dendrogram of Complete Linkage")
plot(train_average, hang = -1, main = "Dendrogram of Average Linkage")
par(mfrow = c(1, 3))
plot(test_single, hang = -1, main = "Dendrogram of Single Linkage")
plot(test_complete, hang = -1, main = "Dendrogram of Complete Linkage")
plot(test_average, hang = -1, main = "Dendrogram of Average Linkage")